%% Extract HRV & EEG relevant features generated by brainbeats_process and 
% output them as a table.
% 
% Cedric Cannard, 2023

function [hrv, eeg] = extract_features(Features)


%% HRV

if isfield(Features,'HRV')
    
    hrv = table.empty;

    % Time
    if isfield(Features.HRV, 'time')
        hrv = struct2table(Features.HRV.time);
    end
    
    % Frequency (average across windows)
    if isfield(Features.HRV, 'frequency')
    
        % list of fields
        features = fieldnames(Features.HRV.frequency);
    
        % ULF
        if sum(contains(features,'ulf')) > 0
            hrv(:,size(hrv,2)+1) = table(mean(Features.HRV.frequency.ulf));
            hrv.Properties.VariableNames(end) = {'ULF-HRV'};
        end
    
        % VLF
        if sum(contains(features,'vlf')) > 0
            hrv(:,size(hrv,2)+1) = table(mean(Features.HRV.frequency.vlf));
            hrv.Properties.VariableNames(end) = {'VLF-HRV'};
        end
    
        % LF
        if sum(contains(features,'lf')) > 0
            hrv(:,size(hrv,2)+1) = table(mean(Features.HRV.frequency.lf));
            hrv.Properties.VariableNames(end) = {'LF-HRV'};
        end
    
        % HF
        if sum(contains(features,'hf')) > 0
            hrv(:,size(hrv,2)+1) = table(mean(Features.HRV.frequency.hf));
            hrv.Properties.VariableNames(end) = {'HF-HRV'};
        end
    
        % LF/HF
        if sum(contains(features,'lfhf')) > 0
            hrv(:,size(hrv,2)+1) = table(mean(Features.HRV.frequency.lfhf));
            hrv.Properties.VariableNames(end) = {'LF/HF'};
        end
    end
    
    % Nonlinear (average across windows)
    if isfield(Features.HRV, 'nonlinear')
    
        % list of fields
        features = fieldnames(Features.HRV.nonlinear);
    
        % Poincare
        if sum(contains(features,'Poincare')) > 0
            hrv(:,size(hrv,2)+1) = table(Features.HRV.nonlinear.Poincare.SD1);
            hrv.Properties.VariableNames(end) = {'Poincaré: SD1'};
    
            hrv(:,size(hrv,2)+1) = table(Features.HRV.nonlinear.Poincare.SD2);
            hrv.Properties.VariableNames(end) = {'Poincaré: SD2'};
    
            hrv(:,size(hrv,2)+1) = table(Features.HRV.nonlinear.Poincare.SD1SD2);
            hrv.Properties.VariableNames(end) = {'SD1/SD2'};
        end
    
        % PRSA
        if sum(contains(features,'PRSA')) > 0
            hrv(:,size(hrv,2)+1) = table(Features.HRV.nonlinear.PRSA_AC);
            hrv.Properties.VariableNames(end) = {'PRSA_AC'};
    
            hrv(:,size(hrv,2)+1) = table(Features.HRV.nonlinear.PRSA_DC);
            hrv.Properties.VariableNames(end) = {'PRSA_DC'};
        end
    
        % Fuzzy entropy
        if sum(contains(features,'FE')) > 0
            hrv(:,size(hrv,2)+1) = table(Features.HRV.nonlinear.FE);
            hrv.Properties.VariableNames(end) = {'HRV-FE'};
        end
    
        % Multiscale fuzzy entropy
        if sum(contains(features,'MFE')) > 0
            % Peak scale number
            [~, peakScale] = max(Features.HRV.nonlinear.MFE);
            hrv(:,size(hrv,2)+1) = table(peakScale);
            hrv.Properties.VariableNames(end) = {'HRV-MFE_peak'};
            
            % Area under the curve (using trapezoidal numerical integration)
            hrv(:,size(hrv,2)+1) = table(trapz(Features.HRV.nonlinear.MFE));
            hrv.Properties.VariableNames(end) = {'HRV-MFE_auc'};
        end
    
    end
end


%% EEG

if isfield(Features,'EEG')
    
    eeg = table.empty;

    % Time
    if isfield(Features.EEG, 'time')
        features = fieldnames(Features.EEG.time);
        for iFeat = 1:length(features)
            fieldname = features{iFeat};
            eeg(:,size(eeg,2)+1) = table(mean(Features.EEG.time.(fieldname)));
            eeg.Properties.VariableNames(end) = {sprintf('EEG-%s', fieldname)};
        end        
    end

    % Frequency
    if isfield(Features.EEG, 'frequency')
        features = fieldnames(Features.EEG.frequency);

        % ULF
        if sum(contains(features,'ulf')) > 0
            eeg(:,size(eeg,2)+1) = table(mean(Features.HRV.frequency.ulf));
            hrv.Properties.VariableNames(end) = {'ULF-HRV'};
        end

    end
end


